---
title: "Consumer Finance Protection Bureau Complaints"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(lubridate)
library(janitor)
library(glue)
library(plotly)
library(DT)
library(htmlwidgets)
library(htmltools)
library(readxl)
library(leaflet)
library(RColorBrewer)
library(htmlwidgets)
library(htmltools)
library(tigris)
library(tmap)
library(tmaptools)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Top Issues

```{r}
complaints <- readRDS("C:/Users/madel/OneDrive/Reporting in the Digital Age/github_repositories/CFPBcomplaints/complaints.rds")

top_issues <- complaints %>%
  group_by(issue) %>%
  summarise(total = n()) %>%
  arrange(desc(total)) %>%
  top_n(5)

fig <- plot_ly(labels = top_issues$issue, values = top_issues$total) %>%
  add_pie(hole = 0.6)
fig
```

Column {data-width=350}
-----------------------------------------------------------------------

### Top Companies

```{r}
complaints <- readRDS("C:/Users/madel/OneDrive/Reporting in the Digital Age/github_repositories/CFPBcomplaints/complaints.rds")

top_companies <- complaints %>%
  group_by(company) %>%
  summarise(total = n()) %>%
  arrange(desc(total)) %>%
  top_n(5)

fig <- plot_ly(
  x = top_companies$company,
  y = top_companies$total,
  name = "Top 5 Companies with Most Complaints",
  type = "bar"
)
fig

```

### Top Products

```{r}
top_products <- complaints %>%
  group_by(product) %>%
  summarise(total = n()) %>%
  arrange(desc(total)) %>%
  top_n(5)

fig <- plot_ly(
  x = top_products$product,
  y = top_products$total,
  name = "Top 5 Products with Most Complaints",
  type = "bar"
)
fig

```

